apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "ServiceAccount" to create, delete, update the configmap in the "flink" namespace.
# You need to already have a Role named "configmap-updater" in that namespace.
kind: RoleBinding
metadata:
  name: configmap-editor
  namespace: flink
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: flink-service-account # "name" is case sensitive
# apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: configmap-updater # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: ""